language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm
matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" STATIC_ANALYSIS=yes
  allow_failures:
    - php: hhvm
    - php: 5.4
    - php: 5.5
before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction ${COMPOSER_FLAGS}
  - if [ "$STATIC_ANALYSIS" != "" ]; then curl -L https://github.com/phpstan/phpstan/releases/download/0.8/phpstan.phar -o phpstan.phar; fi;
script:
  - vendor/bin/phpunit
  - if [ "$STATIC_ANALYSIS" != "" ]; then php phpstan.phar analyse --level=4 src; fi;
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
after_success:
    - bash <(curl -s https://codecov.io/bash)
