# Setup
development:  false
title:        Bandolier
tagline:      Reusable utility functions/methods for use throughout PHP projects!
baseurl:      "/bandolier"
paginate:     1

# About/contact
author:
  name:       Nate Nolting
  url:        https://paulbunyan.net

# Gems/plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
